services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "StockGuard2026!Strong"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: src/StockGuard.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=StockGuardDb;User Id=sa;Password=StockGuard2026!Strong;TrustServerCertificate=true"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      sql:
        condition: service_started
      redis:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: src/StockGuard.Worker/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=StockGuardDb;User Id=sa;Password=StockGuard2026!Strong;TrustServerCertificate=true"
    depends_on:
      sql:
        condition: service_started

volumes:
  sql-data: